AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECR:
    Type: "AWS::ECR::Repository"

Outputs:
  DockerWorkshopRepositoryArn:
    Description: "ARN of the ECR Repository"
    Value: !GetAtt ECR.Arn
    Export:
      Name: DockerWorkshopRepositoryArn
  DockerWorkshopRepository:
    Description: "URL for the repository"
    Value: !Join [ "", [ !Ref "AWS::AccountId", ".dkr.ecr.", !Ref "AWS::Region", ".amazonaws.com/", !Ref ECR ] ]
    Export:
      Name: DockerWorkshopRepository
