AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceName:
    Type: String
  DockerVersion:
    Type: String
  DesiredCount:
    Type: Number
    MinValue: 1
    MaxValue: 6

Resources:
  ServiceTask:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Image: !Join
                 - ""
                 - - !ImportValue DockerWorkshopRepository
                   - ':'
                   - !Ref DockerVersion
          Name: !Join
               - "_"
               - !Split [ "-", !Ref ServiceName ]
          Essential: true
          Cpu: 100
          Memory: 256
          PortMappings:
            - ContainerPort: 8080
              HostPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue 'DockerWorkshopCloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref ServiceName

  Service:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !ImportValue DockerWorkshopECSCluster
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref ServiceTask
